#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Gudu.Resource", IsApplication=true)]

namespace Gudu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::VolleyCSharp.Resource.String.ApplicationName = global::Gudu.Resource.String.ApplicationName;
			global::VolleyCSharp.Resource.String.Hello = global::Gudu.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public const int lineColor = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int tabBackgroundColor = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int tabDark = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int tabMedium = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tabTransparent = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int corner_radius = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int divider_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int small_text_size = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tab_space = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int tab_space_bottom_line = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int tab_space_plus1 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int tab_space_top = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int tab_space_unselected_top = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about_tab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about_tab_select = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int app_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cart_tab = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cart_tab_select = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int class_tab = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int class_tab_select = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int home_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int home_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int index_tab = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int index_tab_select = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int my_tab = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int my_tab_select = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progress_hud_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int search_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int search_selected = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int segment_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int segment_grey = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int segment_grey_focus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int segment_grey_press = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int segment_radio_grey_left = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int segment_radio_grey_left_focus = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int segment_radio_grey_left_press = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int segment_radio_grey_middle = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int segment_radio_grey_middle_focus = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int segment_radio_grey_middle_press = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int segment_radio_grey_right = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int segment_radio_grey_right_focus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int segment_radio_grey_right_press = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int segment_radio_left = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int segment_radio_middle = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int segment_radio_right = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int segment_radio_white_left = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int segment_radio_white_left_focus = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int segment_radio_white_left_press = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int segment_radio_white_middle = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int segment_radio_white_middle_focus = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int segment_radio_white_middle_press = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int segment_radio_white_right = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int segment_radio_white_right_focus = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int segment_radio_white_right_press = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int segment_white = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int segment_white_focus = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int spinner = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int spinner_0 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int spinner_1 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int spinner_10 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int spinner_11 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int spinner_2 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int spinner_3 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int spinner_4 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int spinner_5 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int spinner_6 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int spinner_7 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int spinner_8 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int spinner_9 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int tab_cart = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int tab_focus = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int tab_home = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int tab_indicator = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int tab_mine = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int tab_press = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int tab_search = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int tab_selected = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int tab_unselected = 2130837569;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MvxBindingTagUnique = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int campus_address_textview = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int campus_listview = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int campus_name_textview = 2131230721;
			
			// aapt resource value: 0x7f08000f
			public const int container_view = 2131230735;
			
			// aapt resource value: 0x7f080015
			public const int icon = 2131230741;
			
			// aapt resource value: 0x7f080006
			public const int message = 2131230726;
			
			// aapt resource value: 0x7f080013
			public const int month_sale_textview_id = 2131230739;
			
			// aapt resource value: 0x7f08000e
			public const int radio_comment = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int radio_map = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int radio_menu = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int relativeLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int spinnerImageView = 2131230725;
			
			// aapt resource value: 0x7f080014
			public const int store_brief_textview_id = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int store_list_cell = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int store_listview = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int store_logo_image = 2131230737;
			
			// aapt resource value: 0x7f08000a
			public const int store_name_textview = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int store_name_textview_id = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int textView1 = 2131230728;
			
			// aapt resource value: 0x7f080016
			public const int title = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int top_bar = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int top_radio_button_group = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int arrowspage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CampusListCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int optionspage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int progress_hud = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int select_campus_activity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int store_index_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int StoreListCell = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int tab_indicator = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int tab_main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int tab_1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int tab_2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int tab_3 = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ProgressHUD = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
